tags:
  flipping:
    DOORS: true
    TRAPDOORS: true
    BUTTONS: true
    FENCE_GATES: true

blocks:
  flipping:
    REPEATER: true
    COMPARATOR: true
    OBSERVER: true
    PISTON: true
    STICKY_PISTON: true
    HOPPER: true
    DISPENSER: true
    DROPPER: true

# options: HAND,BAMBOO
tools: "BAMBOO"

translation:
  incorrect_tool: "&aTool is incorrect!"
  reload: "§a[SmartRedstone] Configuration is reloaded!"
  message: "&aThe block has been rotated!"